bundler_args: --without development
before_script:
  - "bundle exec rake db:setup RAILS_ENV=test"
script: "bundle exec rake spec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
gemfile:
  - Gemfile
env:
  - DB=postgresql
branches:
  only:
    - 'master'
